.\" Manpage for print.
.\" Contact on https://github.com/kuba160/print.git to correct errors or 
typos.
.TH man 7 "11 January 2014" "1.0" "print man page"
.SH NAME
print \- prints user's text
.SH SYNOPSIS
print 
.SH DESCRIPTION
print is a program. It prints text
.SH OPTIONS
print does not take any options.
.SH SEE ALSO
echo(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Jakub Wasylkow (kuba160)
Arkadiusz Wasylkow (arwas)
